version: '3'

services:
  client:
    build: ./react-client
    ports:
      - "443:443"
    volumes:
      - ./var:/var/log/nginx/
  server:
    build: ./server
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo
      MONGO_INITDB_ROOT_PASSWORD: Aa123456
    ports:
      - "27017:27017"